n = input('Digite algo:')
print('O tipo primitivo desse valor é: ',type(n))
print('é numerico?',n.isnumeric())
print('é alfabético?',n.isalpha())
print('é alfanumerico?',n.isalnum())
print('Só tem espaço?',n.isspace())
print('Esta capitalizada?',n.istitle())
print('Esta em maiusculo?',n.isupper())
print('Esta em minusculo?',n.islower())
